#!/usr/bin/env python3
"""
Example source plugin demonstrating HA (High Availability) leader election
usage.

This source plugin shows how to use the leader_event, follower_event, and
shutdown_event that are automatically provided when running in HA mode.

The plugin only generates events when it's the leader, and goes dormant when
it's a follower.

Usage in a rulebook:
---
- name: Example HA Rulebook
  hosts: all
  sources:
    - example_ha_source:
        interval: 5
  rules:
    - name: Print event
      condition: event.i is defined
      action:
        debug:

Then run with HA mode:
  ansible-rulebook -r rulebook.yml -i inventory \
    --ha-postgres-dsn \
      "postgresql://eda_user:eda_password@localhost:5432/eda_ha_db" \
    --ha-uuid "550e8400-e29b-41d4-a716-446655440000" \
    --ha-poll-interval 3.0 \
    --ha-worker-id worker-1 \
    -S tests/sources
"""

import asyncio
import logging
from datetime import datetime
from typing import Any, Dict

logger = logging.getLogger(__name__)


async def main(queue: asyncio.Queue, args: Dict[str, Any]):
    """
    Main entry point for the source plugin.

    Args:
        queue: Queue to send events to the rule engine
        args: Arguments from the rulebook, plus HA events if enabled:
              - leader_event: asyncio.Event set when this worker is leader
              - follower_event: asyncio.Event set when this worker is follower
              - shutdown_event: asyncio.Event set when shutting down
    """
    interval = args.get("interval", 10)
    index = args.get("index", 0)

    # Check if HA events are provided
    leader_event = args.get("leader_event")
    follower_event = args.get("follower_event")
    shutdown_event = args.get("shutdown_event")

    if leader_event:
        logger.info(
            "HA mode enabled - source will only generate events when leader"
        )
        await run_with_ha(
            queue,
            interval,
            index,
            leader_event,
            follower_event,
            shutdown_event,
        )
    else:
        logger.info("HA mode not enabled - source will always generate events")
        await run_without_ha(queue, interval, index)


async def run_with_ha(
    queue: asyncio.Queue,
    interval: int,
    index: int,
    leader_event: asyncio.Event,
    follower_event: asyncio.Event,
    shutdown_event: asyncio.Event,
):
    """Run the source plugin in HA mode - only generate events when leader."""
    event_count = index

    try:
        while not shutdown_event.is_set():
            # Wait until we become leader
            logger.info("Waiting to become leader...")
            await leader_event.wait()

            logger.info("🎯 BECAME LEADER - Starting event generation")

            # Generate events while we're the leader
            while leader_event.is_set() and not shutdown_event.is_set():
                event_count += 1
                event = {
                    "i": event_count,
                    "timestamp": datetime.now().isoformat(),
                    "message": (
                        f"Event generated by leader (total: {event_count})"
                    ),
                    "role": "leader",
                }

                logger.info(
                    "🎯 Generating event #%d (leader mode)", event_count
                )
                await queue.put(event)
                await asyncio.sleep(interval)

            # Lost leadership
            if not shutdown_event.is_set():
                logger.info(
                    "💤 LOST LEADERSHIP - Stopping event generation "
                    "(generated %d events total)",
                    event_count,
                )

        logger.info("Shutdown signal received - exiting")

    except asyncio.CancelledError:
        logger.info(
            "Source plugin cancelled (generated %d events total)", event_count
        )
        raise


async def run_without_ha(queue: asyncio.Queue, interval: int, index: int):
    """Run the source plugin without HA - always generate events."""
    event_count = index

    try:
        while True:
            event_count += 1
            event = {
                "i": event_count,
                "timestamp": datetime.now().isoformat(),
                "message": f"Event generated (no HA) (total: {event_count})",
                "role": "standalone",
            }

            logger.info("Generating event #%d (standalone mode)", event_count)
            await queue.put(event)
            await asyncio.sleep(interval)

    except asyncio.CancelledError:
        logger.info(
            "Source plugin cancelled (generated %d events total)", event_count
        )
        raise


if __name__ == "__main__":
    # For testing the plugin directly
    class MockQueue:
        async def put(self, event):
            print(f"EVENT: {event}")

    async def test():
        queue = MockQueue()
        args = {"interval": 2}
        await main(queue, args)

    asyncio.run(test())
